sudo: required
dist: trusty
language:
  - java
jdk:
  - oraclejdk8 # Building Bazel requires JDK8.
before_install:
  - sudo apt-get update
  # http://bazel.io/docs/install.html
  - sudo apt-get install -y pkg-config zip g++ zlib1g-dev unzip
  - wget https://github.com/bazelbuild/bazel/releases/download/0.3.0/bazel_0.3.0-linux-x86_64.deb.sha256
  - wget https://github.com/bazelbuild/bazel/releases/download/0.3.0/bazel_0.3.0-linux-x86_64.deb
  - sha256sum -c bazel_0.3.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.3.0-linux-x86_64.deb
script:
  - bazel test //tests/...
  - bazel build //docs/...
